### PR TITLE
#8  db authentication provider implemented

### PR DESCRIPTION
**Pull request by gaua**

### CODE REVIEW

**Comment by azalut** [comment]
In the UserController isnt it better to obtain username and password from RequestParam (for example when sending it through HTML forms)

**Comment by gaua** [comment]
Yes, it is. If you mean insertWithUsernameAndPassword action, it has to be removed when we finish user registration form.

**Comment by azalut** [comment]
ok got it, and what about using User entity constructor in UserDao implementation instead of setting every field one by one? only few lines of code less but still something :)

**Comment by gaua** [comment]
Great idea ;)

**Pull request merged**
